var products = [{
    "id": 0,
    "title": "",
    "price": "",
    "description": "",
    "benefits": "",
    "file_compatibility": "",
    "open_geomap": "",
    "add_xref": "",
    "insert_pdf": "",
    "coordinate_sys": "",
    "dimensions": "",
    "block_att": "",
    "layer_interface": "",
    "note_on_text": "",
    "performance": "",
    "use_cases": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png"
}, 
{
    "id": 1,
    "title": "AutoCAD",
    "price": ["Monthly: SGD 372", 
                "Annually: SGD 2,968", 
                "Every 3 years: SGD 8,456"],
    "description": "AutoCAD is a commercial computer-aided design (CAD) and drafting software application. Developed and marketed by Autodesk.",
    "benefits": ["Has both 2D and 3D modelling functionality",
                "Can use without internet as it utilises local and network files",
                "Has been the go-to CAD software for decades"],
    "file_compatibility": ["Open: dwg, dxf, wmf, emf, wmz, emz, dae, dgn, 3dm, skp, ifc, rfa,rvt", 
                            "Save to: dwg, dxf", 
                            "Export to: Fbx, svg, stl, dgn, dae, 3dm, ifc"],
    "open_geomap": "Yes",
    "add_xref": "Yes",
    "insert_pdf": "Yes",
    "coordinate_sys": "Able to set coordinate system",
    "dimensions": "Yes",
    "block_att": "Yes",
    "layer_interface": "Yes",
    "note_on_text": "Need to raise a IT ticket for the installation of text style types",
    "performance": "Time to open 500 files: 18 min 39 sec <br /><br />Time to run advanced LISP routine: 49 min",
    "use_cases": "When you prefer a familiar software with a large community to help.",
    "image": "https://aux3.iconspalace.com/uploads/6399511681435985048.png"
}, 
{
    "id":2,
    "title": "BricsCAD",
    "price": ["BricsCAD Lite: US$590", 
                "BricsCAD Pro: US$1,150", 
                "BricsCAD BIM: US$1,890",
                "BricsCAD Mechanical: US$1,780",
                "**Perpetual License**"],
    "description": "BricsCAD is a software application for computer-aided design (CAD), developed by Bricsys nv. In 2018, Bricsys nv was acquired in full by Hexagon AB of Sweden",
    "benefits": ["DWG Compatible", 
                "Instantly familiar to AutoCAD users", 
                "Automatic configuration and customisation transfer",
                "Intelligent CAD tools",
                "2.7x faster in opening drawings (opening 500+ drawings)"],
    "file_compatibility": ["Open: dwg, dxf, wmf, emf, wmz, emz, dae, dgn, 3dm, skp, ifc, rfa,rvt", 
                            "Save to: dwg, dxf", 
                            "Export to: Fbx, svg, stl, dgn, dae, 3dm, ifc"],
    "open_geomap": "BricsCAD Pro is unable to do this. BricsCAD Platinum is required to do this.",
    "add_xref": "Yes",
    "insert_pdf": "Yes, and the insertion is better in BricsCAD compared to AutoCAD as well. c turns the linework into “polyline” whilst AutoCAD turn the linework in “line”.",
    "coordinate_sys": "Able to set coordinate system and original coordinate system set in AutoCAD is retained when opening with BricsCAD",
    "dimensions": "Yes",
    "block_att": "Yes and can be modified from original AutoCAD file",
    "layer_interface": "Similar to Autodesk AutoCAD/Civil3d product - very user friendly",
    "note_on_text": "Need to raise a IT ticket for the installation of text style types ",
    "performance": "Time to open 500 files: 6 min 51 sec <br /><br />Time to run advanced LISP routine: 17 min",
    "use_cases": "A suitable software for quick simple tasks such as open up the drawing to add/amends text/dimensions, change title block, change layer properties and print/plot it out.",
    "image": "https://logovectordl.com/wp-content/uploads/2020/03/bricscad-logo-vector.png"
}, 
{
    "id": 3,
    "title": "MicroStation",
    "price": ["BricsCAD Lite: US$590", 
                "BricsCAD Pro: US$1,150", 
                "BricsCAD BIM: US$1,890",
                "BricsCAD Mechanical: US$1,780"],
    "description": "MicroStation is a CAD software platform for two- and three-dimensional design and drafting, developed and sold by Bentley Systems and used in the architectural and engineering industries. It generates 2D/3D vector graphics objects and elements and includes building information modeling (BIM) features. The current version is MicroStation CONNECT Edition.",
    "benefits": [""],
    "file_compatibility": ["Open: dwg, dxf, wmf, emf, wmz, emz, dae, dgn, 3dm, skp, ifc, rfa,rvt", 
                            "Save to: dwg, dxf", 
                            "Export to: Fbx, svg, stl, dgn, dae, 3dm, ifc"],
    "open_geomap": "",
    "add_xref": "",
    "insert_pdf": "",
    "coordinate_sys": "",
    "dimensions": "",
    "block_att": "",
    "layer_interface": "",
    "note_on_text": "",
    "performance": "",
    "use_cases": "",
    "image": "https://applet3d.com/wp-content/uploads/2022/03/micro-station.png"
}]